export const SCHOOL = {
  DOCUMENT_NAME: 'School',
  COLLECTION_NAME: 'schools',
  PREFIX: 'sch_',
  MODEL: {
    MAM_NON: 'mam-non',
    TIEU_HOC: 'tieu-hoc',
    TTTA: 'trung-tam-tieng-anh',
    TTDN: 'trung-tam-day-nhac',
    TTDT: 'trung-tam-day-toan',
    TTTN: 'trung-tam-tieng-nhat',
    TTDB: 'trung-tam-day-boi',
    TTTT: 'trung-tam-tieng-trung',
    DH: 'dai-hoc',
    CD: 'cao-dang',
    TCN: 'trung-cap-nghe',
    TT: 'trong-tre',
    TTTH: 'trung-tam-tieng-han',
    THCS: 'trung-hoc-co-so',
    THPT: 'trung-hoc-pho-thong',
    TTLTDH: 'trung-tam-luyen-thi-dai-hoc',
    TTLTC3: 'trung-tam-luyen-thi-cap-3',
    TTTP: 'trung-tam-tieng-phap',
  },
  TYPE: {
    TU_THUC: 'tu-thuc',
    CONG_LAP: 'cong-lap',
    SONG_NGU: 'song-ngu',
    QUOC_TE: 'quoc-te',
  },
  PROGRAM: {
    CBGD: 'chuan-bo-giao-duc',
    GAKKEN: 'gakken-steam-program',
    STEAM: 'steam',
    MONTESSORI: 'montessori',
    SHICHIDA: 'shichida',
    GLENN_DOMAN: 'glenn-doman',
    HIGHSCOPE: 'highscope',
    REGGIO_EMILIA: 'reggio-emilia',
    IEYC: 'ieyc',
    EYFS: 'eyfs',
    NEL: 'nel',
  },
} as const;
